<<<<<<< HEAD
services: 
 vareapi: 
<<<<<<< HEAD
     image: louiseellegaard/vareapi:latest-dev 
=======
     image: louiseellegaard/vareapi:latest-dev
>>>>>>> efa5abfaf27258e3096521f72c418de9aa5d31cc
     ports:  
     - "8080:80" 
     environment: 
     - TaxaBookingBrokerHost=rabbitmq-dev 
     depends_on: 
     - rabbitmq-dev 
 budapi: 
<<<<<<< HEAD
     image: louiseellegaard/budapi:latest-dev 
=======
     image: louiseellegaard/budapi:latest-dev
>>>>>>> efa5abfaf27258e3096521f72c418de9aa5d31cc
     ports: 
     - "8081:80" 
     environment: 
     - TaxaBookingBrokerHost=rabbitmq-dev 
     depends_on: 
     - rabbitmq-dev 
 kundeapi: 
<<<<<<< HEAD
     image: louiseellegaard/kundeapi:latest-dev 
=======
     image: louiseellegaard/kundeapi:latest-dev
>>>>>>> efa5abfaf27258e3096521f72c418de9aa5d31cc
     ports: 
     - "8082:80" 
     environment: 
     - TaxaBookingBrokerHost=rabbitmq-dev 
     depends_on: 
     - rabbitmq-dev 
 rabbitmq-dev: 
     image: rabbitmq:management 
     ports: 
     - "15672:15672" 
     - "5672:5672"
=======
version: '3.4'

services:
  vareservice:
    image: louiseellegaard/vareapi:latest-dev
    ports:
      - "8080:80"

  kundeservice:
    image: louiseellegaard/kundeapi:latest-dev
    ports:
      - "8081:80"

  budservice:
    image: louiseellegaard/budapi:latest-dev
    ports:
      - "8082:80"
    depends_on:
      - rabbitmq-dev

  rabbitmq-dev:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
>>>>>>> 3564cdd6c4a2cc4daa1830ad34c9fb021cd7d3f9
