services: 
 vareapi: 
     image: vareapitest:latest
     ports:  
     - "8080:80" 
     environment: 
     - TaxaBookingBrokerHost=rabbitmq-dev 
     depends_on: 
     - rabbitmq-dev 
 budapi: 
     image: louiseellegaard/budapi:latest-dev
     ports: 
     - "8081:80" 
     environment: 
     - TaxaBookingBrokerHost=rabbitmq-dev 
     depends_on: 
     - rabbitmq-dev 
 kundeapi: 
     image: louiseellegaard/kundeapi:latest-dev
     ports: 
     - "8082:80" 
     environment: 
     - TaxaBookingBrokerHost=rabbitmq-dev 
     depends_on: 
     - rabbitmq-dev 
 rabbitmq-dev: 
     image: rabbitmq:management 
     ports: 
     - "15672:15672" 
     - "5672:5672"
  
 nginx:
     image: nginx:latest
     volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
     depends_on:
      - kundeapi
      - vareapi
     ports:
      - "4000:4000"
