services:

 vareservice:
     image: louiseellegaard/vareapi:latest-dev
     hostname: vareservice
     environment:
      - ConnectionString=mongodb+srv://louisedb:louisedb123@auktionshusdb.upg5v0d.mongodb.net/?retryWrites=true&w=majority
      - Database=Auktiondb
      - Collection=Vare
     expose:
     - "80"

 budservice:
     image: louiseellegaard/budapi:latest-dev
     hostname: budservice
     environment:
      - ConnectionString=mongodb+srv://louisedb:louisedb123@auktionshusdb.upg5v0d.mongodb.net/?retryWrites=true&w=majority
      - Database=Auktiondb
      - Collection=Bud
      - BidBrokerHost=rabbitmq
     depends_on:
     - rabbitmq
     restart: unless-stopped
     expose:
     - "80"

 kundeservice:
     image: louiseellegaard/kundeapi:latest-dev
     hostname: kundeservice
     environment:
      - ConnectionString=mongodb+srv://louisedb:louisedb123@auktionshusdb.upg5v0d.mongodb.net/?retryWrites=true&w=majority
      - Database=Auktiondb
      - Collection=Kunde
     expose:
     - "80"

 auktionservice:
     image: louiseellegaard/auktionapi:latest-dev
     hostname: auktionservice
     environment:
      - ConnectionString=mongodb+srv://louisedb:louisedb123@auktionshusdb.upg5v0d.mongodb.net/?retryWrites=true&w=majority
      - Database=Auktiondb
      - Collection=Auktion
     expose:
     - "80"

 indexservice:
     image: louiseellegaard/indexapi:latest-dev
     hostname: indexservice
     environment:
     - BidBrokerHost=rabbitmq
     depends_on:
     - rabbitmq
     expose:
     - "80"

 rabbitmq:
     image: rabbitmq:management
     hostname: "rabbitmq"
     container_name: "rabbitmq"
     ports:
     - "5672:5672"
     - "15672:15672"

 nginx:
     image: nginx:latest
     container_name: "gateway"
     volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/www/data
     restart: unless-stopped
     depends_on:
      - kundeservice
      - vareservice
      - budservice
      - auktionservice
      - indexservice
     ports:
      - "4000:4000"

networks:
  default:
    driver: bridge
    name: auktionshus