name: Docker Image CI for VareApi

on:
  push:
    branches: [ "develop" ]
    paths: [ "Vare Service/VareApi/**" ]
  pull_request:
    branches: [ "develop" ]
    paths: [ "Vare Service/VareApi/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub 
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      run: 
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
        
    - name: Build the Docker image for VareApi 
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }} 
      run: docker build . --file "Vare Service/VareApi/Dockerfile" --tag ${DOCKER_USER}/vareapi:latest-dev
      
    - name: Push Docker image to Docker Hub 
      env: 
       DOCKER_USER: ${{ secrets.DOCKER_USER }} 
      run: docker push ${DOCKER_USER}/vareapi:latest-dev
